name: Deploy Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0

      - name: Update GitHub Packages source with credentials
        run: dotnet nuget update source "github" --username Infohubsite --password ${{ secrets.NUGET_GITHUB_PAT }} --store-password-in-clear-text

      - name: Restore dependencies
        run: dotnet restore Frontend.csproj

      - name: Generate Build Info File
        env:
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          echo '{' > wwwroot/build-info.json
          echo '  "commitMessage": ${{ toJSON(env.COMMIT_MESSAGE) }},' >> wwwroot/build-info.json
          echo '  "buildTime": "'$(date -u --iso-8601=seconds)'"' >> wwwroot/build-info.json
          echo '}' >> wwwroot/build-info.json

      - name: Publish .NET Project
        run: dotnet publish Frontend.csproj --configuration Release --output build --no-restore

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build/wwwroot

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        
