name: Deploy Pages

on:
  push:
    branches: [ main ]

# Sets permissions for the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0 # Or your target .NET version

      # *** NEW STEP ADDED HERE ***
      - name: Generate Build Info File
        run: |
          echo '{' > Frontend/wwwroot/build-info.json
          echo '  "commitMessage": "${{ github.event.head_commit.message }}",' >> Frontend/wwwroot/build-info.json
          echo '  "buildTime": "'$(date -u --iso-8601=seconds)'"' >> Frontend/wwwroot/build-info.json
          echo '}' >> Frontend/wwwroot/build-info.json
        # IMPORTANT: Replace "Frontend" with the name of your Blazor project directory.

      - name: Publish .NET Project
        run: dotnet publish Frontend.csproj --configuration Release --output build
        # IMPORTANT: Ensure "Frontend.csproj" is the correct path to your .csproj file.

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build/wwwroot

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
